- hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
  roles:
    - docker-install
    - backend-deployment
    - frontend-deployment
    - setup-mongodb
   