apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: monica-yolo-client
        image: monica8531/yolo-client:v1.0.0
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cd /app && npm run build && npx serve -s build -l 3000"]